### ISSUE TITLE
An struct.error occurred 

### ISSUE THREAD

**Issue by Logend2** [penn5/logo-xiaomi#1]
An error occurred,When I was unpacking MI8-Lite logo.
corrupt bmp header skipping
corrupt bmp header skipping
Traceback (most recent call last):
  File "D:\mi5备份\修改第一屏\新建文件夹\logo-xiaomi.py", line 132, in <module>
    main()
  File "D:\mi5备份\修改第一屏\新建文件夹\logo-xiaomi.py", line 116, in main
    print(args.pop("func")(**args))
  File "D:\mi5备份\修改第一屏\新建文件夹\logo-xiaomi.py", line 120, in extract_logo
    for photo in extract(input):
  File "D:\mi5备份\修改第一屏\新建文件夹\logo-xiaomi.py", line 59, in extract
    (header, size) = unpack("<2sI", f.read(6))
struct.error: unpack requires a buffer of 6 bytes
![TIM截图20191201113320.png](https://i.loli.net/2019/12/01/KthP15md7L3y4oY.png)

**Comment by penn5** [comment]
The file does not follow the same format as Cepheus.
