### ISSUE TITLE
Idk why, but crash

### ISSUE THREAD

**Issue by xiaoniaoawa** [penn5/logo-xiaomi#3]
When I unpack my image on mix2s's official pack, it works well.
but crash when replace new image:
`
D:\ulk\AI_logo-xiaomi>python logo-xiaomi.py replace -i logo.img -o logo_new.img -a ./logo/logo-0.bmp -a ./logo/logo-1.bmp -a ./logo/logo-2.bmp -a ./logo/logo-3.bmp -a ./logo/logo-4.bmp -a ./logo/logo-5.bmp -a ./logo/logo-6.bmp -a ./logo/logo-7.bmp
Traceback (most recent call last):
  File "D:\ulk\AI_logo-xiaomi\logo-xiaomi.py", line 132, in <module>
    main()
  File "D:\ulk\AI_logo-xiaomi\logo-xiaomi.py", line 116, in main
    print(args.pop("func")(**args))
  File "D:\ulk\AI_logo-xiaomi\logo-xiaomi.py", line 127, in replace_logo
    out = edit(input, [i.read() for i in images])
  File "D:\ulk\AI_logo-xiaomi\logo-xiaomi.py", line 73, in edit
    raise ValueError("All images must be replaced")
ValueError: All images must be replaced

D:\ulk\AI_logo-xiaomi>
`

**Comment by penn5** [comment]
You should list images then replace all of them.
